server:
  port: 8902
spring:
  application:
    name: im-tcp
  rabbitmq:
    host: 192.168.101.65
    port: 5672
    virtualHost: /dangren
    username: dangren
    password: dangren
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        retry:
          enabled: true
BootstrapConfig:
  TcpConfig:
    tcpPort: 9001
    webSocketPort: 19001
    bossThreadSize: 1
    workThreadSize: 8
    heartBeatTime: 3000 #心跳超时时间 单位毫秒
    brokerId: 1002
    loginModel: 3
    #  *                多端同步模式：1 只允许一端在线，手机/电脑/web 踢掉除了本client+imel的设备
    #  *                            2 允许手机/电脑的一台设备 + web在线 踢掉除了本client+imel的非web端设备
    #  *                            3 允许手机和电脑单设备 + web 同时在线 踢掉非本client+imel的同端设备
    #  *                            4 允许所有端多设备登录 不踢任何设备
redis:
  mode: single #单机模式 哨兵模式sentinel  集群模式 cluster
  database: 0
  password: 123456
  timeout: 3000 #超时时间
  poolMinIdle: 8 #最小空闲数
  poolConnectTimeout: 3000 #连接超时时间
  poolSize: 10 #连接池大小
  single:
    address: 127.0.0.1:6379
rabbitmq:
  host: 192.168.101.65
  port: 5672
  virtualHost: /dangren
  userName: dangren
  password: dangren
zkConfig:
  zkAddr: 127.0.0.1:2181
  zkConnectTimeOut: 5000
