server:
  port: 8901
spring:
  application:
    name: im-tcp
BootstrapConfig:
  TcpConfig:
    tcpPort: 9000
    webSocketPort: 19000
    bossThreadSize: 1
    workThreadSize: 8
    heartBeatTime: 20000 #心跳超时时间 单位毫秒